### PR TITLE
Adding Enter-to-submit capability on all demos

### PR DESCRIPTION
**Pull request by aaronsarnat**
Fixes [Enter doesn't submit a query to process results (#14)](https://github.com/allenai/allennlp-demo/issues/14)

---

Tested all fields on all demos.

### CODE REVIEW

**Comment by schmmd** [comment]
Cool, looks good but I wonder--is there any way to handle this in a more general fashion so we don't need this code for each page?  @joelgrus any ideas here?

**Comment by aaronsarnat** [comment]
@schmmd that thought crossed my mind as well, but there is already a ton of duplicated code in the same vein, and I wasn't sure if I should try to introduce a new paradigm for this task. We don't really have a place for general util functions currently, but we probably should.

TBH I think the whole demo front-end could use a refactor / refresh, as it's a bit of a mess currently, but that seems like a separate effort that I believe you were saying we probably don't want to worry about in Q3.

That said, if you want me to work on generalizing this particular function, I am happy take another stab.

**Comment by joelgrus** [comment]
I agree that (1) this code probably should be written only once and (2) that probably can't happen until we do a larger refactor

**Comment by schmmd** [comment]
Thanks--if you have any specific ideas on a refactor I'd love to hear them :https://github.com/allenai/allennlp-demo/issues/43

**Pull request merged**
