### PR TITLE
[DRAFT] Attempt at starting demo for LERC

### PR DESCRIPTION
**Pull request by anthonywchen**
Hello!

I've begun the process of adding a learned metric: [LERC](https://arxiv.org/abs/2010.03636) to the AllenNLP demo. 

In particular, I've done the added/modified the following:
- `ui/src/components/demos/EvaluateReadingComprehension.js` This has the UI for LERC.
- `ui/src/models.js` I've updated this to load the previous file.
- `api/allennlp_demo/lerc` I've copied over @nitishgupta NMN code since that also uses an external Git repo and modified it for LERC.

Things that aren't done yet:
- The model archive path is not finished. I will send this model archive soon to be uploaded!
- The `<Output>` section in EvaluateReadingComprehension.js is not yet complete.
- I'm not sure if my API files in `api/allennlp_demo/lerc/` are written correctly. 

Any help you could provide in looking over these files and any issues you find that I should fix would be greatly appreciated!

Thanks for your help! Best,
Anthony

### CODE REVIEW

**Comment by anthonywchen** [comment]
Adding @dirkgr to this. Thanks Dirk!

**Comment by dirkgr** [comment]
Thanks for adding me! If this is not ready for merging, can you mark it as a "draft"? Then it shows up properly in the UI,  and hides potentially dangerous "merge" buttons.

Did you need me to upload a file for you?

**Comment by anthonywchen** [comment]
Done! I sent an email to your gmail with the link to the model archive. Let me know if there any issues with the link or not getting the email :)

**Comment by dirkgr** [comment]
The file is now available at https://storage.googleapis.com/allennlp-public-models/lerc-2020-11-18.tar.gz.

**Comment by anthonywchen** [comment]
Thank you very much! I'll update the link in the model.json file.

**Comment by jonborchardt** [comment]
BTW, there have been HUGE changes in how new demos are added to allennlp
please reach out to me BEFORE working any more on this pr
(it likely needs to be scraped)

**Review by jonborchardt — CHANGES_REQUESTED** [review]
BTW, there have been HUGE changes in how new demos are added to allennlp
please reach out to me BEFORE working any more on this pr
(it likely needs to be scraped)

**Comment by anthonywchen** [comment]
Thanks for letting me know! I will check out the new demo repo before adding anything.

**Comment by dirkgr** [comment]
Since https://github.com/allenai/allennlp-demo/pull/909 is merged, can we close this one?

**Comment by anthonywchen** [comment]
Yes, thanks Dirk!

**Pull request closed without merging**
