### PR TITLE
Add usage information to Sentiment Analysis

### PR DESCRIPTION
**Pull request by schmmd**
@Eric-Wallace could you additionally add instructions for evaluating and training?  It would look like this: https://github.com/allenai/allennlp-demo/blob/master/demo/src/components/demos/ReadingComprehension.js#L580

Feel free to push commits directly to this PR.

### CODE REVIEW

**Comment by Eric-Wallace** [comment]
i don't have write access, so I can't push here =(

**Comment by schmmd** [comment]
@Eric-Wallace just sent you an invite to the AllenNLP team in GitHub, which should fix the problem.

**Comment by Eric-Wallace** [comment]
great, I also added this https://github.com/allenai/allennlp/pull/3320 for the training config.

**Comment by Eric-Wallace** [comment]
@schmmd think this PR is good to go.

**Pull request merged**
