### PR TITLE
Update DB with request before predicting.

### PR DESCRIPTION
**Pull request by brendan-ai2**
- This will allow us to track down "queries of death".
- In service of https://github.com/allenai/allennlp-demo/issues/37.
- Also includes a script and instructions for running a local development DB.

### CODE REVIEW

**Comment by brendan-ai2** [comment]
Do we have a copy of the SQL needed to start up a local copy of the DB for development? I wrote a unit test for this change, but I should probably validate against an actual postgres before pushing to prod. Though maybe staging is sufficient?

**Comment by schmmd** [comment]
@brendan-ai2 staging uses the prod database.  I don't have such a query.

**Comment by brendan-ai2** [comment]
I'll try to extract it from the DB with `pg_dump`.

**Comment by schmmd** [comment]
I.e. we could extend https://github.com/allenai/allennlp-demo/blob/d1b5ce0651074b2ca5cc4f9fa4ec8d050b199eb5/app.py#L259 by logging the requests as they come in (say, here https://github.com/allenai/allennlp-demo/blob/d1b5ce0651074b2ca5cc4f9fa4ec8d050b199eb5/app.py#L178).

**Comment by schmmd** [comment]
@brendan-ai2 that should work.  There are only 1 or 2 tables as I recall.

**Comment by brendan-ai2** [comment]
Thanks for the review! Yeah, I had the same thought about logging, but initially decided against as it makes the logs slightly harder to read. Super minor issue though.

I managed to get the schema with `pg_dump`. I'll clean that up and get it working for creating a local DB tomorrow when I'm back in the office.

**Comment by brendan-ai2** [comment]
Updated with a script + instructions on setting up a DB locally for development. Sure enough, this caught a typo in my SQL. Going to go ahead and merge now that that's fixed!

**Pull request merged**
