### PR TITLE
update tugboat to 2.0.3

### PR DESCRIPTION
**Pull request by aimichal**
This updates AllenNLP demo to use Tugboat 2.0.3: https://github.com/allenai/tugboat/releases/tag/v2.0.3

### CODE REVIEW

**Review by mkusold — APPROVED** [review]
👍

**Comment by aimichal** [comment]
Confirmed the demo runs locally and I can submit and get responses as expected.

The funny $5 million byte problem is fixed: https://github.com/allenai/tugboat/pull/14

And when the backend 500s, instead of

> Promise failure: SyntaxError: Unexpected token < in JSON at position 0

I see

> Promise failure: Error: Something went wrong; server response status was 500

like this:

image

(I can't explain why this 500s.)

**Comment by aimichal** [comment]
I'll merge and deploy this in the morning.

**Review by jonborchardt — APPROVED** [review]
yup

**Pull request merged**
