### PR TITLE
Update demos to use RC3.

### PR DESCRIPTION
**Pull request by schmmd**

### CODE REVIEW

**Comment by schmmd** [comment]
```
Traceback (most recent call last):
  File "/usr/local/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/allennlp/__main__.py", line 19, in run
    main(prog="allennlp")
  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/__init__.py", line 93, in main
    args.func(args)
  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/predict.py", line 255, in _predict
    manager.run()
  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/predict.py", line 229, in run
    for model_input_json, result in zip(batch_json, self._predict_json(batch_json)):
  File "/usr/local/lib/python3.6/site-packages/allennlp/commands/predict.py", line 175, in _predict_json
    results = [self._predictor.predict_json(batch_data[0])]
  File "/usr/local/lib/python3.6/site-packages/allennlp/predictors/predictor.py", line 66, in predict_json
    return self.predict_instance(instance)
  File "/usr/local/lib/python3.6/site-packages/allennlp/predictors/predictor.py", line 189, in predict_instance
    outputs = self._model.forward_on_instance(instance)
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/model.py", line 141, in forward_on_instance
    return self.forward_on_instances([instance])[0]
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/model.py", line 167, in forward_on_instances
    outputs = self.make_output_human_readable(self(**model_input))
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/basic_classifier.py", line 173, in make_output_human_readable
    for token_id in instance_tokens
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/basic_classifier.py", line 173, in <listcomp>
    for token_id in instance_tokens
  File "/usr/local/lib/python3.6/site-packages/allennlp/data/vocabulary.py", line 665, in get_token_from_index
    return self._index_to_token[namespace][index]
KeyError: 1596
2020-04-29 21:47:53,636 - INFO - allennlp.models.archival - removing temporary unarchived model dir at /tmp/tmpo8baxaor
```

**Comment by schmmd** [comment]
I'm pretty sure this is a regression from `1.0.0rc1`.  I ran the following under ``:

```bash
echo '{"hypothesis": "Two women are sitting on a blanket near some rocks talking about politics.", "premise": "Two women are wandering along the shore drinking iced tea."}' | allennlp predict --predictor textual-entailment --include-package allennlp_models https://storage.googleapis.com/allennlp-public-models/snli-roberta-large-2020.02.27.tar.gz -
```
```
input 0:  {"hypothesis": "Two women are sitting on a blanket near some rocks talking about politics.", "premise": "Two women are wandering along the shore drinking iced tea."}
prediction:  {"logits": [-4.040728569030762, 3.5561299324035645, 1.1318645477294922], "probs": [0.0004609781608451158, 0.9182355403900146, 0.08130345493555069], "label": "contradiction"}
```

**Comment by dirkgr** [comment]
This might still not work. I have a new problem now locally.

**Comment by dirkgr** [comment]
Alright, this should be it now.

**Pull request merged**
