### PR TITLE
Fix many, but not all of the models

### PR DESCRIPTION
**Pull request by dirkgr**
This is mostly @ZhaofengWu's coref changes, and my scattered fixes to various models. It is not complete, but I think we should get this merged, since it at least improves the situation.

### CODE REVIEW

**Comment by dirkgr** [comment]
This currently depends on https://github.com/allenai/allennlp-models/pull/10, but once that is merged I will update the link here.

**Comment by dirkgr** [comment]
Forgot to mention: I have already reviewed @ZhaofengWu's part, so you don't have to analyze every line as you go through it.

**Comment by schmmd** [comment]
I'm deploying an ad-hoc (https://allennlp-demo.fix-everything.apps.allenai.org).

**Comment by schmmd** [comment]
Here's a list of what still isn't working.  My suggestion is that we should pin these items and move on:

* NER (I am investigating and likely broke this)
* Dependencing Parsing
* This list is in progress... stay tuned...

**Comment by schmmd** [comment]
```
kubectl logs allennlp-demo-fix-everything-dependency-parsing-99ccfbd54-d4cd9 --namespace=allennlp-demo dependency-parsing
{"message": "Starting a flask server on port 8000.", "severity": "INFO"}
{"message": "With models {'dependency-parsing': <server.demo_model.DemoModel object at 0x7fb1cc9b75f8>}", "severity": "INFO"}
{"message": "loading dependency-parsing model", "severity": "INFO"}
100%|██████████| 73229020/73229020 [00:01<00:00, 62482611.07B/s]
Did not use initialization regex that was passed: .*bias_hh.*
Did not use initialization regex that was passed: .*bias_ih.*
Did not use initialization regex that was passed: .*weight_ih.*
Did not use initialization regex that was passed: .*weight_hh.*
Traceback (most recent call last):
  File "./app.py", line 532, in <module>
    models=models)
  File "./app.py", line 99, in main
    app = make_app(build_dir=f"{demo_dir}/build", demo_db=demo_db, models=models)
  File "./app.py", line 131, in make_app
    predictor = demo_model.predictor()
  File "/stage/allennlp/server/demo_model.py", line 25, in predictor
    archive = load_archive(self.archive_file)
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/archival.py", line 186, in load_archive
    cuda_device=cuda_device,
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/model.py", line 341, in load
    return model_class._load(config, serialization_dir, weights_file, cuda_device)
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/model.py", line 289, in _load
    model.load_state_dict(model_state)
  File "/usr/local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 830, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for BiaffineDependencyParser:
	Missing key(s) in state_dict: "encoder._module.forward_layer_0.cell.input_linearity.weight", "encoder._module.forward_layer_0.cell.state_linearity.weight", "encoder._module.forward_layer_0.cell.state_linearity.bias", "encoder._module.backward_layer_0.cell.input_linearity.weight", "encoder._module.backward_layer_0.cell.state_linearity.weight", "encoder._module.backward_layer_0.cell.state_linearity.bias", "encoder._module.forward_layer_1.cell.input_linearity.weight", "encoder._module.forward_layer_1.cell.state_linearity.weight", "encoder._module.forward_layer_1.cell.state_linearity.bias", "encoder._module.backward_layer_1.cell.input_linearity.weight", "encoder._module.backward_layer_1.cell.state_linearity.weight", "encoder._module.backward_layer_1.cell.state_linearity.bias", "encoder._module.forward_layer_2.cell.input_linearity.weight", "encoder._module.forward_layer_2.cell.state_linearity.weight", "encoder._module.forward_layer_2.cell.state_linearity.bias", "encoder._module.backward_layer_2.cell.input_linearity.weight", "encoder._module.backward_layer_2.cell.state_linearity.weight", "encoder._module.backward_layer_2.cell.state_linearity.bias". 
	Unexpected key(s) in state_dict: "encoder._module.forward_layer_0.input_linearity.weight", "encoder._module.forward_layer_0.state_linearity.weight", "encoder._module.forward_layer_0.state_linearity.bias", "encoder._module.backward_layer_0.input_linearity.weight", "encoder._module.backward_layer_0.state_linearity.weight", "encoder._module.backward_layer_0.state_linearity.bias", "encoder._module.forward_layer_1.input_linearity.weight", "encoder._module.forward_layer_1.state_linearity.weight", "encoder._module.forward_layer_1.state_linearity.bias", "encoder._module.backward_layer_1.input_linearity.weight", "encoder._module.backward_layer_1.state_linearity.weight", "encoder._module.backward_layer_1.state_linearity.bias", "encoder._module.forward_layer_2.input_linearity.weight", "encoder._module.forward_layer_2.state_linearity.weight", "encoder._module.forward_layer_2.state_linearity.bias", "encoder._module.backward_layer_2.input_linearity.weight", "encoder._module.backward_layer_2.state_linearity.weight", "encoder._module.backward_layer_2.state_linearity.bias". 
```
```
kubectl logs allennlp-demo-fix-everything-elmo-snli-5bf7bb788d-7n78j --namespace=allennlp-demo elmo-snli
{"message": "Starting a flask server on port 8000.", "severity": "INFO"}
{"message": "With models {'elmo-snli': <server.demo_model.DemoModel object at 0x7f96e27ba5c0>}", "severity": "INFO"}
{"message": "loading elmo-snli model", "severity": "INFO"}
100%|██████████| 697659182/697659182 [00:11<00:00, 58511996.12B/s]
100%|██████████| 336/336 [00:00<00:00, 904548.23B/s]
100%|██████████| 374434792/374434792 [00:06<00:00, 59967021.08B/s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/params.py", line 237, in pop
    value = self.params.pop(key)
KeyError: 'matrix_attention'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./app.py", line 532, in <module>
    models=models)
  File "./app.py", line 99, in main
    app = make_app(build_dir=f"{demo_dir}/build", demo_db=demo_db, models=models)
  File "./app.py", line 131, in make_app
    predictor = demo_model.predictor()
  File "/stage/allennlp/server/demo_model.py", line 25, in predictor
    archive = load_archive(self.archive_file)
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/archival.py", line 186, in load_archive
    cuda_device=cuda_device,
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/model.py", line 341, in load
    return model_class._load(config, serialization_dir, weights_file, cuda_device)
  File "/usr/local/lib/python3.6/site-packages/allennlp/models/model.py", line 278, in _load
    model = Model.from_params(vocab=vocab, params=model_params)
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/from_params.py", line 552, in from_params
    **extras,
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/from_params.py", line 580, in from_params
    kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/from_params.py", line 164, in create_kwargs
    cls.__name__, param_name, annotation, param.default, params, **extras
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/from_params.py", line 263, in pop_and_construct_arg
    popped_params = params.pop(name, default) if default != _NO_DEFAULT else params.pop(name)
  File "/usr/local/lib/python3.6/site-packages/allennlp/common/params.py", line 239, in pop
    raise ConfigurationError(f'key "{key}" is required at location "{self.history}"')
allennlp.common.checks.ConfigurationError: key "matrix_attention" is required at location "model."
```

```
kubectl logs allennlp-demo-fix-everything-fine-grained-ner-7c679fbb6b-2fws5 --namespace=allennlp-demo fine-grained-ner
Traceback (most recent call last):
  File "./app.py", line 526, in <module>
    models = load_demo_models(args.models_file, args.model, model_names_only=args.no_models)
  File "/stage/allennlp/server/models.py", line 34, in load_demo_models
    model = blob[task_name]
KeyError: 'fine-grained-ner'
```

**Comment by dirkgr** [comment]
Even though this is not complete, I will merge this. It makes a bunch of things better, and it's awkward to send people links to my own private branch.

**Pull request merged**
