### PR TITLE
combine all javascript updates

### LINKED ISSUE #370: Combine all the dependably version updates
We have a bunch of queued up dependably version updates. We should combine them into one and test it, then commit all at once.

### PR DESCRIPTION
**Pull request by epwalsh**
closes #370

### CODE REVIEW

**Comment by dirkgr** [comment]
Screen Shot 2020-04-27 at 17 09 15
This is how you become top contributor for the week :-)

**Comment by dirkgr** [comment]
Maybe I jumped the gun testing this, but this does not build:
```
Failed to compile.

./src/components/demos/TextualEntailment.js
Attempted import error: 'AccordionItemBody' is not exported from 'react-accessible-accordion'.


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! demo@0.1.0 build: `react-app-rewired build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the demo@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dirkg/.npm/_logs/2020-04-28T00_13_59_588Z-debug.log
Traceback (most recent call last):
  File "./scripts/build_demo.py", line 7, in <module>
    run('npm run build', shell=True, check=True, cwd='demo')
  File "/Users/dirkg/anaconda3/envs/allennlp-demo/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'npm run build' returned non-zero exit status 1.
```

**Comment by epwalsh** [comment]
We should probably add to our CI checks then

**Comment by dirkgr** [comment]
Where is this at? Is it enough to just not update `react-accessible-accordion` so much?

**Comment by epwalsh** [comment]
That should be enough, I'll give it a try

**Comment by epwalsh** [comment]
@dirkgr this should build now

**Pull request merged**
