### PR TITLE
Update AllenNLP commit used by the VQA model.

### PR DESCRIPTION
**Pull request by codeviking**
...as it looks like the referenced commit was squashed out of existence.

This commit marks the release of `1.1.0`, which is what's reported by [here](https://demo.allennlp.org/api/vilbert-vqa/).

### CODE REVIEW

**Comment by dirkgr** [comment]
Since the vision branch is not released yet, version 1.1 won't work. This has to point to the top of the vision branch.

**Comment by dirkgr** [comment]
There might be some changes to how the dataset reader is constructed. There was a parameter called `skip_something`, which is now inverted and called `run_something`.

**Comment by codeviking** [comment]
@dirkgr I tried that, now it fails at runtime:

```
model_1       | Traceback (most recent call last):
model_1       |   File "/usr/local/lib/python3.7/site-packages/allennlp/common/params.py", line 238, in pop
model_1       |     value = self.params.pop(key)
model_1       | KeyError: 'image_biattention_id'
model_1       |
model_1       | During handling of the above exception, another exception occurred:
model_1       |
model_1       | Traceback (most recent call last):
model_1       |   File "allennlp_demo/vilbert_vqa/api.py", line 53, in <module>
model_1       |     endpoint = VilbertVqaModelEndpoint()
model_1       |   File "allennlp_demo/vilbert_vqa/api.py", line 14, in __init__
model_1       |     super().__init__(c)
model_1       |   File "/app/allennlp_demo/common/http.py", line 89, in __init__
model_1       |     self.predictor = model.load_predictor()
model_1       |   File "/app/allennlp_demo/common/config.py", line 103, in load_predictor
model_1       |     archive = load_archive(self.archive_file, overrides=o)
model_1       |   File "/usr/local/lib/python3.7/site-packages/allennlp/models/archival.py", line 208, in load_archive
model_1       |     model = _load_model(config.duplicate(), weights_path, serialization_dir, cuda_device)
model_1       |   File "/usr/local/lib/python3.7/site-packages/allennlp/models/archival.py", line 246, in _load_model
model_1       |     cuda_device=cuda_device,
model_1       |   File "/usr/local/lib/python3.7/site-packages/allennlp/models/model.py", line 406, in load
model_1       |     return model_class._load(config, serialization_dir, weights_file, cuda_device)
model_1       |   File "/usr/local/lib/python3.7/site-packages/allennlp/models/model.py", line 305, in _load
model_1       |     vocab=vocab, params=model_params, serialization_dir=serialization_dir
model_1       |   File "/usr/local/lib/python3.7/site-packages/allennlp/common/from_params.py", line 599, in from_params
model_1       |     **extras,
model_1       |   File "/usr/local/lib/python3.7/site-packages/allennlp/common/from_params.py", line 627, in from_params
model_1       |     kwargs = create_kwargs(constructor_to_inspect, cls, params, **extras)
model_1       |   File "/usr/local/lib/python3.7/site-packages/allennlp/common/from_params.py", line 199, in create_kwargs
model_1       |     cls.__name__, param_name, annotation, param.default, params, **extras
model_1       |   File "/usr/local/lib/python3.7/site-packages/allennlp/common/from_params.py", line 301, in pop_and_construct_arg
model_1       |     popped_params = params.pop(name, default) if default != _NO_DEFAULT else params.pop(name)
model_1       |   File "/usr/local/lib/python3.7/site-packages/allennlp/common/params.py", line 243, in pop
model_1       |     raise ConfigurationError(msg)
model_1       | allennlp.common.checks.ConfigurationError: key "image_biattention_id" is required at location "model."
allennlp-demo_model_1 exited with code 1
```

@dirkgr I think it'd likely be more effective to have you debug this, since you're intimately familiar with the AllenNLP bits and I know nothing of those, Jon Snow.  Do you mind taking a stab at this?

**Comment by codeviking** [comment]
Also, for reference, here's how you start things locally with a local instance of the VQA model:

```
MODEL_DOCKERFILE=allennlp_demo/vilbert_vqa/Dockerfile MODEL=vilbert_vqa docker-compose up --build
```

If you want logs from just the model endpoint, run:

```
docker-compose logs model
```

**Comment by dirkgr** [comment]
:+1: I'll take care of it.

**Comment by dirkgr** [comment]
Man, these issues take forever to work on when you're not spun up. Step 1: Download stuff for 30 minutes. I'll have to get better internet or something.

**Comment by dirkgr** [comment]
This model works, in the sense that it loads up fine. But I suspect it's blind, due to a bug that @epwalsh found.

**Comment by dirkgr** [comment]
Can we let this sit over the weekend and see if @epwalsh has something better by Monday? The models are all a-trainin'.

**Comment by codeviking** [comment]
Yup, sure. I merged the PR that was blocked by the CI target, as I was fairly certain my TypeScript wasn't breaking the VQA model :).

**Comment by dirkgr** [comment]
The new model is still training :-/

**Comment by codeviking** [comment]
@dirkgr Any update here? CI is still failing, so we're currently merging with regard for it -- I'd hate to break things further :).

**Review by dirkgr — APPROVED** [review]

**Pull request merged**
